dist: trusty
language: java
sudo: false
jdk: openjdk8
script: export INST_HOME=$JAVA_HOME/jre; mvn install -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn